version: "3"

dotenv: [".env"]

tasks:
  install:
    cmds:
      - uv sync --dev
      - uv run pre-commit install

  run:
    cmds:
      - uv run reflex run

  test:
    cmds:
      - uv run ruff check --fix
      - uv run pyright
      - uv run pytest

  watch-tests:
    cmds:
      - find tests mcp_chat -type f -path "*.py" | entr uv run pytest

  pre-commit-all:
    cmds:
      - uv run pre-commit run --all-files

  jupyter:
    cmds:
      - uv run --with jupyterlab --with jupyterlab-vim jupyter lab

  bump-patch:
    cmds:
      - uv run hatch version patch

  bump-minor:
    cmds:
      - uv run hatch version minor

  bump-major:
    cmds:
      - uv run hatch version major

  publish:
    preconditions:
      - sh: git status
    cmds:
      - git diff --quiet --staged || (echo "There are staged changes. They must be committed first" && exit 1)
      - git diff --quiet || (echo "There are unstaged changes. They must be committed first." && exit 1)

      - uv run hatch version | xargs -I {} git tag -a v{} -m "Release v{}"
      - git push --follow-tags
