name: CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.13"]
    environment:
      name: ci

    steps:
      - uses: actions/checkout@v4

      # # Fail fast if required env vars are not set
      # - name: Check env vars set
      #   run: |
      #     if [ -z "${{ vars.NOT_SO_SECRET }}" ]; then
      #       echo "NOT_SO_SECRET is not set"
      #       exit 1
      #     fi
      #     if [ -z "${{ secrets.VERY_SECRET }}" ]; then
      #       echo "VERY_SECRET is not set"
      #       exit 1
      #     fi
      #
      # - name: Create .env
      #   run: |
      #     echo "SOME_SECRET=${{ secrets.SOME_SECRET }}" >> .env

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.12"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: uv sync --group test

      - name: Lint
        run: uv run ruff check

      - name: Type check
        run: uv run pyright

      - name: Run tests
        run: uv run pytest
